# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2025 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: job
  id: OutpostSyndicateShareholder
  name: job-name-outpost-syndicate-shareholder
  description: job-description-outpost-syndicate-shareholder
  playTimeTracker: JobOutpostSyndicateShareholder
  whitelisted: true
  startingGear: OutpostSyndicateShareholderGear
  canBeAntag: false
  hideConsoleVisibility: true
  icon: "JobIconSyndicateShareholder"
  supervisors: job-supervisors-hire
  setPreference: true
  access:
  - SyndicateAgent
  - NuclearOperative
  accessGroups:
  - AllAccess
  special:
  - !type:AddComponentSpecial
    components:
      - type: Company
        companyName: Syndicate
      - type: SpecialSectorStationRecord
        recordGeneration: FalseRecord
      - type: MailDisabled
      - type: NpcFactionMember
        factions:
        - LuaNordFoll
  - !type:AddImplantSpecial
    implants: [ TrackingImplantNordfoll ]

- type: startingGear
  id: OutpostSyndicateShareholderGear
  equipment: {}

- type: chameleonOutfit
  id: OutpostSyndicateShareholderChameleonOutfit
  job: OutpostSyndicateShareholder


